import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/pages/shared/navbar/Navbar";
import Header from "@/pages/shared/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
